version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins_server_hospital
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home: