"""did relationshio corrections

Revision ID: e628a215708c
Revises: f108899c06c7
Create Date: 2025-09-19 17:48:44.773732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e628a215708c'
down_revision: Union[str, Sequence[str], None] = 'f108899c06c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('patients', sa.Column('given_name', sa.String(), nullable=False))
    op.drop_column('patients', 'give_name')
    op.drop_column('patients', 'tenat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('tenat_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('give_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('patients', 'given_name')
    op.drop_column('patients', 'tenant_id')
    # ### end Alembic commands ###
